name: Atualizar Contador

on:
  schedule:
    - cron: '0 0 * * *'  # Executa diariamente à meia-noite UTC

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Executar script de atualização
        run: python update_counter.py

      - name: Commit e Push se houver alterações
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add contador.json README.md
          git commit -m "Atualização automática do contador" || echo "Nada para atualizar"
          git push
